### ISSUE TITLE
Add Windows.ApplicationModel.Store.dll crack in dll injector

### ISSUE THREAD

**Issue by ValZapod** [notcarlton/OnixLauncher#1]
https://github.com/sr-pato/MinecraftBedrock

Does not make the market free unfortunately. Works even on 1.18 latest beta.

**Comment by ValZapod** [comment]
I do not want the real dll to be touched, just injected, also they updated recently, may be nice to decypher the real hex change here, also should not use any dll injection not compativle with secure boot.

**Comment by notcarlton** [comment]
onix isn't for piracy and never will be

**Comment by Itsbryan8228** [comment]
Ok
