### ISSUE TITLE
launching while the game is open doesn't work for most (new) users

### ISSUE THREAD

**Issue by phasephasephase** [notcarlton/OnixLauncher#14]
this was an intended feature when the launcher first came out, but after a DLL update, the launcher broke itself and now it doesn't work anymore

if you've used the launcher since release then this probably still works for you
it works for me, so i can't really fix it

people tend to treat the launcher like an injector and open the game before clicking launch so we need to fix this as soon as possible

**Comment by h-m-m-m** [comment]
cant you just kill it and then open again?

**Comment by phasephasephase** [comment]
people inject during gameplay too, so this is unsafe and also very invasive to the end user

**Comment by h-m-m-m** [comment]
maybe prompt to close the game?

**Comment by phasephasephase** [comment]
this is something i've considered but i would like to at least try to fix the feature before dropping it entirely

**Comment by phasephasephase** [comment]
this seems to have magically fixed itself and now it's erroring when the game is open and nothing happens. i already implemented an error message when this is the case, so now we don't have to tell anyone to do this
