### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by Douloureux** [notcarlton/OnixLauncher#15]
I want to build the client from source, but the dependencies are not installing due to expired certificates and not being trusted:
`
Error	NU3028	Package 'DiscordRichPresence 1.0.175' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider.	OnixLauncher	D:\src\OnixLauncher\OnixLauncher\OnixLauncher.csproj	1	
`

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU3037	Package 'DiscordRichPresence 1.0.175' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.	OnixLauncher	D:\src\OnixLauncher\OnixLauncher\OnixLauncher.csproj	1	
`

`
Error	NU3028	Package 'Microsoft.PowerShell.5.ReferenceAssemblies 1.1.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider.	OnixLauncher	D:\src\OnixLauncher\OnixLauncher\OnixLauncher.csproj	1	
`

`
Error	NU3037	Package 'DiscordRichPresence 1.0.175' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.	OnixLauncher	D:\src\OnixLauncher\OnixLauncher\OnixLauncher.csproj	1	
`

Is there any way I can bypass these checks?

**Comment by h-m-m-m** [comment]
you dont, fix it einstein

**Comment by phasephasephase** [comment]
i've had a few people build the launcher and they didn't have this problem, so i can't find the exact cause

not sure how to fix this

**Comment by h-m-m-m** [comment]
i am trying to fix it, the problem is that the packages like guna ui (ew not wpf), Costura Fody and rpc not being restored correctly

**Comment by phasephasephase** [comment]
it is back

**Comment by h-m-m-m** [comment]
#16
