### ISSUE TITLE
Support for Education Edition

### ISSUE THREAD

**Issue by lemonyte** [notcarlton/OnixLauncher#25]
It would be nice if the launcher could inject the Onix Client into Minecraft Education Edition. This might need a bit of work since
1. Education Edition is on a different version than Bedrock Edition
2. Would need some UI interface to select between the Education and Bedrock
3. Would need to detect if Education Edition is installed

I am willing to work on this feature. Let me know if it is possible to download client DLLs by Minecraft version.

**Comment by phasephasephase** [comment]
this has to do with the DLL and onix isn't willing to add support for education edition
