### ISSUE TITLE
Zooming does not affect hand in first-person (2.72rc2)

### ISSUE THREAD

**Issue by Scienceguy458** [notcarlton/OnixLauncher#29]
I was experimenting with something and needed to zoom in, but then realized my hand was not being affected. Here is a video:

https://user-images.githubusercontent.com/99567833/165016000-a89a511c-d884-4ccf-8381-f5a846661861.mp4

**Comment by bernarddesfosse** [comment]
Thats how 1.18.30 reacts to the zoom, in the Zoom settings there will be an option to hide the hand while zooming so if it annoys you just check there next update, also to report client bugs please make a ticket in the discord, this is the launcher repository.
