### ISSUE TITLE
Minecraft 1.17.41.6 crashes in the new update

### ISSUE THREAD

**Issue by Anozz1124** [notcarlton/OnixLauncher#33]
I used An injector that day An It Was Fine. And I Saw An Youtube Video, That Gives New Features To Onix Client. So I Updated The DLL's From Discord, And Also The Injector. But When I Injected it My Game Crashed, I Know There Are Other Client's But This is my Favorite One. So pl,s Fix this.

**Comment by h-m-m-m** [comment]
dude update to 1.18

**Comment by h-m-m-m** [comment]
also this issue is about the injector so please go to the discord.

**Comment by phasephasephase** [comment]
pp
