### ISSUE TITLE
naming conventions and code style

### ISSUE THREAD

**Issue by phasephasephase** [notcarlton/OnixLauncher#4]
we should come up with a naming convention for this thing

oh and code style too

**Comment by ghost** [comment]
public function sendResponse(): string { return "EZ"; }

**Comment by Zeyrox1090** [comment]
code

**Comment by JustSxm** [comment]
2 Space Tabs
aVariableName
AFunctionName();
use CodeMaid.

**Comment by phasephasephase** [comment]
i think rider's default naming convention and style are good except constant variables:

UPPER_SNAKE_CASE

the rest:
_privateField
PublicField (or property)
ClassName
NamespaceName
MethodName(firstParam, secondParam ...)
methodVariable

**Comment by ghost** [comment]
What's wrong with const var `UPPER_SNAKE_CASE` (Rider)?

**Comment by phasephasephase** [comment]
> What's wrong with const var `UPPER_SNAKE_CASE` (Rider)?

oh i meant that rider doesn't do `UPPER_SNAKE_CASE`, instead they do PascalCase for constant fields

**Comment by ghost** [comment]
Pretty sure you can edit Naming Convention in Rider.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/79522460/160432542-4624346a-76df-4d39-917d-33df268c47f6.png)

**Comment by ghost** [comment]
Use Rider instead of Visual Studio!
